# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AcneTreatment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'CYLTabBarController'
pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'Masonry'
pod 'YYCache'
pod 'KLCPopup'
pod 'Toast'
end
